import { IAccount,IProfile, IArticle, IArticleAddCommentRequestParams, IArticleCreateRequestParams, IArticleGetListRequestParams, IArticleList, IArticleUpdateRequestParams, IComment, IWallet } from "./models";


export const iAccountMock : IAccount = {
    id: 4,
    name: "ban_1astrkqrn98arxtnmz6nda8cc5of48ftnxjh3u7r9nsdfdcdjqs6fwx6dj33",
    address: "ban_1astrkqrn98arxtnmz6nda8cc5of48ftnxjh3u7r9nsdfdcdjqs6fwx6dj33",
    description: "This account generated by the system",
    balance: 0,
    pending: 0,
    enabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    walletId: 12
}

export const iwalletMock : IWallet = {

    id:             12,
    name: "generated_banano_wallet_0.7943035860523775",
    description: "wallet genereated by the system",
    balance: 0,
    pending: 0,
    enabled: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    seed: "3CDC495D7EA187B1BC9EF66CF4379919AD2CF41D1B6CA5F2C8D71804FDF8A270",
    mnemonic: "",
    deleted: false,
    userId: 2,
    accounts: [iAccountMock]
}

export const iprofileMock: IProfile = {
    username: 'serhatt',
    bio: 'comoputer enginner',
    image: null,
    following: true
} as IProfile

export const articleMock1: IArticle = {
    slug: '234sdsfds',
    title: 'Test Article',
    description: 'this is genereated in the code',
    body: 'I am larning new UI framework. Vue.js is simple and lightweight..I like it.',
    tagList: ['tag1', 'tag2'],
    createdAt: new Date(),
    updatedAt: new Date(),
    favorited: true,
    favoritesCount: 55,
    author: iprofileMock
};

export const articleMock2: IArticle = {
    slug: '22232332',
    title: 'What the fuck article',
    description: 'Go fuck yourself bitch yo yo yo yo',
    body: 'gues whos is back. Shady is back. Back again....',
    tagList: ['shady', 'rap'],
    createdAt: new Date(),
    updatedAt: new Date(),
    favorited: true,
    favoritesCount: 444,
    author: iprofileMock
};

const articleArray: IArticle[] = [
    articleMock1,
    articleMock2
];

export const articleListMock: IArticleList = {
    articles: articleArray,
    articlesCount: 2,
};

export const commentMock: IComment = {
    id: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    body: "my comment bitch",
    author: iprofileMock
}